service: kakaobob-lambda

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-add-api-key

custom:
  ENV_CONFIG: ${file(./config/config.js):ENV_CONFIG}
  apiKeys:
    - name: kakaobob_key
      value: ${self:custom.ENV_CONFIG.MY_X_API_KEY}

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  memorySize: 1024
  timeout: 30
  environment:
    MY_AWS_ACCESSKEY_ID: ${self:custom.ENV_CONFIG.MY_AWS_ACCESSKEY_ID}
    MY_AWS_SECRET_ACCESS_KEY: ${self:custom.ENV_CONFIG.MY_AWS_SECRET_ACCESS_KEY}
    MY_X_API_KEY: ${self:custom.ENV_CONFIG.MY_X_API_KEY}

functions:
  main:
    handler: src/controller.main
    events:
      - http:
          path: /message
          method: post
          cors: true
          private: true
