service: kakaobob-lambda

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-add-api-key

custom:
  apiKeys:
    - name: kakaobob_key
      value: ${env.X_API_KEY}

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  memorySize: 1024
  timeout: 30
  environment:
    MY_AWS_ACCESSKEY_ID: ${env.AWS_ACCESSKEY_ID}
    MY_AWS_SECRET_ACCESS_KEY: ${env.AWS_SECRET_ACCESS_KEY}
    MY_X_API_KEY: ${env.MY_X_API_KEY}

functions:
  main:
    handler: src/controller.main
    events:
      - http:
          path: /message
          method: post
          cors: true
          private: true
